config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root to: 'tweets#index'
  resources :tweets do
    resources :comments, only: :create
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '~10代' },
    { id: 3, name: '10代' },
    { id: 4, name: '20代' },
    { id: 5, name: '30代' },
    { id: 6, name: '40代' },
    { id: 7, name: '50代' },
    { id: 8, name: '60代' },
    { id: 9, name: '70代' },
    { id: 10, name: '80代～' }
  ]

  include ActiveHash::Associations
  has_many :users

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet, optional: true
  belongs_to :user

  validates :text, presence: true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '男性' },
    { id: 3, name: '女性' },
  ]

  include ActiveHash::Associations
  has_many :users

  end

app/models/residence.rb
class Residence < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '山梨県' },
    { id: 17, name: '長野県' },
    { id: 18, name: '新潟県' },
    { id: 19, name: '富山県' },
    { id: 20, name: '石川県' },
    { id: 21, name: '福井県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' },
  ]

  include ActiveHash::Associations
  has_many :users
  has_many :items

  end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :residence

  validates :residence_id, numericality: { other_than: 1 , message: "can't be blank"} 
  validates :title, presence: true, length: { maximum: 30 }
  validates :text, presence: true, length: { maximum: 100 }
  validates :image, presence: true
  validates :city, :spot, length: { maximum: 30 }

  belongs_to :user
  has_many :comments 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  belongs_to :age
  belongs_to :residence
  
  has_many :tweets
  has_many :comments

  validates :nickname, presence: true, length: { maximum: 8 }
  validates :profile, presence: true, length: { maximum: 15 }
  validates :gender_id, :residence_id, :age_id, numericality: { other_than: 1 , message: "can't be blank"} 
  validates :password, length: { minimum: 6 }, format: { with: /\A[a-zA-Z0-9]+\z/, message: "は半角英数字で入力してください" }, on: :create
  validates :password, presence: true, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :gender_id, :profile, :residence_id, :age_id])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :profile, :gender_id, :residence_id, :age_id])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    redirect_to "/tweets/#{@comment.tweet.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: [:index, :edit, :show]
  before_action :set_tweet, only: [:edit, :show, :update, :destroy]

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    unless current_user == @tweet.user
      redirect_to root_path
    end
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def destroy
    @tweet.comments.destroy_all
    @tweet.destroy
    redirect_to root_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:residence_id, :title, :text, :city, :spot, :shooting_day, :image).merge(user_id: current_user.id)

  end

  def move_to_index
    redirect_to root_path unless user_signed_in?
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @user = user
    @tweets = @user.tweets
  end

  def edit
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trip360</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@700&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @tweet.errors.any? %>
<div class="error-alert">
  <ul>
    <% @tweet.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/tweets/edit.html.erb
<div class="new-post">
  <header class="new-header">
    <h1><%= link_to image_tag("logo.png", class: "logo-new", alt: "Trip360°"), root_path %></h1>
    <h3 class="post-heading">編集する</h3>
  </header>

  <div class="contents-row">
    <div class="contents">
      <div class="container">
        <%= form_with(model: @tweet, local: true, class: "my-form-class") do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

          <div class="img-upload">
            <div class="weight-bold-text">
            商品画像
              <span class="indispensable">※必須</span>
            </div>
            <div class="click-upload">
              <p>
              クリックしてファイルをアップロード
              </p>
              <%= f.file_field :image, id:"tweet-image" %>
            </div>
          </div>
          <div class="weight-bold-text">
          <p>時期</p>
          <%= f.date_field :shooting_day, placeholder: "2024/01/01", class: "form-class"%>
          </div>
          <div class="weight-bold-text">
          <p>場所 <span class="indispensable">※必須</span></p>
          <%= f.collection_select(:residence_id, Residence.all, :id, :name, {}, {class:"form-class", id:"item-category"}) %>
          </div>
          <div class="weight-bold-text">
          <p>場所</p>
          <%= f.text_field :city, placeholder: "市町村を入力", class: "form-class"%>
          </div>
          <div class="weight-bold-text">
          <p>スポット名</p>
          <%= f.text_field :spot, placeholder: "スポット名を入力", class: "form-class"%>
          </div>
          <div class="weight-bold-text">
          <p>タイトル <span class="indispensable">※必須</span></p>
          <%= f.text_field :title, placeholder: "タイトルを入力(30文字まで)", rows: "10",class: "form-class" %>
          </div>
          <div class="weight-bold-text">
          <p>コメント <span class="indispensable">※必須</span></p>
          <%= f.text_area :text, placeholder: "体験や感想、おススメな点など(100文字まで)", class: "form-class" %>
          </div>
          <%= f.submit "更新する", class: "send-class" %>
        <% end %>
      </div>
    <div>
  <div>
  <footer>
  </footer>
</div>

app/views/tweets/index.html.erb
<div id="home" class="big-bg">
  <header class="page-header wrapper">
    <h1><%= link_to image_tag("logo.png", class: "logo", alt: "Trip360°"), root_path %></h1>
    <nav>
    <% if user_signed_in? %>
      <ul class="main-nav">
        <li><%= link_to '投稿する', new_tweet_path, class: "post" %></li> 
        <li><%= link_to 'マイページ', "/users/#{current_user.id}", class: "post"%></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "post" %></li>
      </ul>
      <p class="welcome">ようこそ <%= current_user.nickname %> さん</p>
    <% else %>
      <ul class="main-nav">
        <li><%= link_to 'ログイン', new_user_session_path, class: "post" %></li> 
        <li><%= link_to '新規登録', new_user_registration_path, class: "post" %></li>
      </ul>
    <% end %>
    </nav>
  </header>

  <div class="home-content wrapper">
    <h2 class="page-title">Share your wonderful photos</h2>
    <P>素敵な写真を共有しましょう</P>
  </div>
</div>

<h3>最新投稿一覧</h3>

<div class="grid">
  <ul class='tweet-list'>
    <% @tweets.each do |tweet| %>
    <li class="tweet-item">
      <div class="tweet-name">
        <%= link_to tweet.user.nickname, user_path(tweet.user) %>
      </div>
      <div class="tweet-image">
        <%= link_to tweet_path(tweet) do %>
          <%= image_tag tweet.image.variant(resize: '600x300') if tweet.image.attached? %>
        <% end %>
      </div>
      <div class="tweet-title">
        <p><%= tweet.title %></p>
      </div>
    </li>
    <% end %>
  </ul>
<div>
<footer>
</footer>

app/views/tweets/new.html.erb
<div class="new-post">
  <header class="new-header">
    <h1><%= link_to image_tag("logo.png", class: "logo-new", alt: "Trip360°"), root_path %></h1>
    <h3 class="post-heading">投稿する</h3>
  </header>

  <div class="contents-row">
    <div class="contents">
      <div class="container">
        <%= form_with(model: @tweet, local: true, class: "my-form-class") do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

          <div class="img-upload">
            <div class="weight-bold-text">
            画像
              <span class="indispensable">※必須</span>
            </div>
            <div class="click-upload">
              <p>
              クリックしてファイルをアップロード
              </p>
              <%= f.file_field :image, id:"tweet-image" %>
            </div>
          </div>
          <div class="weight-bold-text">
          <p>時期</p>
          <%= f.date_field :shooting_day, placeholder: "2024/01/01", class: "form-class"%>
          </div>
          <div class="weight-bold-text">
          <p>場所 <span class="indispensable">※必須</span></p>
          <%= f.collection_select(:residence_id, Residence.all, :id, :name, {}, {class:"form-class", id:"item-category"}) %>
          </div>
          <div class="weight-bold-text">
          <p>場所</p>
          <%= f.text_field :city, placeholder: "市町村を入力", class: "form-class"%>
          </div>
          <div class="weight-bold-text">
          <p>スポット名</p>
          <%= f.text_field :spot, placeholder: "スポット名を入力", class: "form-class"%>
          </div>
          <div class="weight-bold-text">
          <p>タイトル <span class="indispensable">※必須</span></p>
          <%= f.text_field :title, placeholder: "タイトルを入力(30文字まで)", rows: "10",class: "form-class" %>
          </div>
          <div class="weight-bold-text">
          <p>コメント <span class="indispensable">※必須</span></p>
          <%= f.text_area :text, placeholder: "体験や感想、おススメな点など(100文字まで)", class: "form-class" %>
          </div>
          <%= f.submit "投稿する", class: "send-class" %>
        <% end %>
      </div>
    <div>
  <div>
  <footer>
  </footer>
</div>

app/views/tweets/show.html.erb
<div class="new-post">
  <header class="new-header">
    <h1><%= link_to image_tag("logo.png", class: "logo-new", alt: "Trip360°"), root_path %></h1>
    <h3 class="post-heading">投稿詳細</h3>
  </header>
  
  <div class="itemshows-contents">
    <div class="itemshow-contents">
      <div class="user-show-title">
        <p style="word-wrap: break-word;"><%= @tweet.title %></p>
      </div>
      <div class="user-show-image">
        <%= image_tag @tweet.image.variant(resize: '600x300'), class: "full-width" if @tweet.image.attached? %>
      </div>
      <div class="user-show-day">
        <p><%= @tweet.shooting_day %></p>
      </div>
      <div class="user-show-text">
        <p style="word-wrap: break-word;"><%= @tweet.text %></p>
      </div>
      <div class="user-show-residence">
        <p>場所:<%= @tweet.residence.name %><%= @tweet.city %> </p>
      </div>
      <div class="user-show-residence">
        <p>スポット名：<%= @tweet.spot %> </p>
      </div>
      <% if current_user == @tweet.user %>
      <div class="edit-link">
        <%= link_to "編集する", edit_tweet_path(@tweet), class: "edit-show" %>
        <%= link_to "削除する", "/tweets/#{@tweet.id}", data: { turbo_method: :delete }, class: "edit-show" %>
      </div>
      <% end %>
    </div>
    <div class="comment-contents">
    <% if user_signed_in? %>
      <%= form_with(model: [@tweet, @comment], local: true, html: { class: "comment-form" }) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
  <footer>
  </footer>
<div>

app/views/users/show.html.erb
<div class="show-user">
  <header class="new-header">
    <h1><%= link_to image_tag("logo.png", class: "logo-new", alt: "Trip360°"), root_path %></h1>
  </header>

  <div class="show-profile">
    <p class="user-nickname"><%= @user.nickname %></p>
    <div class="user-show-field">
      <div class="user-show-label">
      <%= @user.profile %>
      </div>
      <div class="user-show-label">
      <%= @user.residence.name %>
      </div>
      <div class="user-show-label">
      <%= @user.gender.name %>(<%= @user.age.name %>)
      </div>
      <% if user_signed_in? && current_user.id == @user.id %>
      <div class="user-edit-link">
        <%= link_to '編集する', edit_user_registration_path, class: "show" %>
      <% else %>
      <div class="user-edit-link-2">
      </div>
      <% end %>
    </div>
  </div>

  <div class="show-contents">
    <p class="user-nickname-index"><%= @user.nickname %>さんの投稿一覧</p>
    <% @tweets.each do |tweet| %>
    <div class="user-show">
      <div class="user-show-line"></div>
      <div class="user-show-title">
        <p style="word-wrap: break-word;"><%= tweet.title %></p>
      </div>
      <div class="user-show-image">
        <%= link_to tweet_path(tweet) do %>
        <%= image_tag tweet.image.variant(resize: '600x300'), class: "full-width" if tweet.image.attached? %>
        <% end %>
      </div>
      <div class="user-show-day">
        <p><%= tweet.shooting_day %></p>
      </div>
      <div class="user-show-text">
        <p style="word-wrap: break-word;"><%= tweet.text %></p>
      </div>
      <div class="user-show-residence">
        <p>場所:<%= tweet.residence.name %><%= tweet.city %> </p>
      </div>
      <div class="user-show-residence">
        <p>スポット名：<%= tweet.spot %> </p>
      </div>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <div class="edit-link">
          <%= link_to "編集する", edit_tweet_path(tweet), class: "edit-show" %>
          <%= link_to '削除する', "/tweets/#{tweet.id}", data: { turbo_method: :delete }, class: "show" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<footer>
</footer>